FROM python:3.8-slim-buster

WORKDIR /scripts

COPY requirements.txt .
COPY scripts/ .
COPY .env .

RUN apt-get update && apt-get install ffmpeg -y && \
    pip install -r requirements.txt && \
    ffdl install --add-path -y

CMD ["python3", "main.py"]