FROM python:3.11-slim

WORKDIR /scripts

COPY requirements.txt .
COPY scripts/ .
COPY .env .

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install ffmpeg -y && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    ffdl install --add-path -y

CMD ["python3", "main.py"]